image: docker:stable

stages:
  - build
  - deploy

variables:
  CLIENT_IMAGE_NAME: $CI_REGISTRY_IMAGE/isari-client:$CI_COMMIT_REF_SLUG
  API_IMAGE_NAME: $CI_REGISTRY_IMAGE/isari-api:$CI_COMMIT_REF_SLUG

build_client:
  stage: build
  script:
    - docker build -t $CLIENT_IMAGE_NAME -f ./client/Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CLIENT_IMAGE_NAME
  environment:
    name: staging
    url: $STAGING_BASEURL
  only:
    - master
    - prod

build_api:
  stage: build
  script:
    - docker build -t $API_IMAGE_NAME -f Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $API_IMAGE_NAME
  environment:
    name: staging
    url: $STAGING_BASEURL
  only:
    - master
    - prod
