image: docker:stable

stages:
  - build
  - deploy

variables:
  CLIENT_IMAGE_NAME: $CI_REGISTRY_IMAGE/isari-client:$CI_COMMIT_REF_SLUG
  API_IMAGE_NAME: $CI_REGISTRY_IMAGE/isari-api:$CI_COMMIT_REF_SLUG

build_client:
  stage: build
  script:
    - docker build -t $CLIENT_IMAGE_NAME -f ./client/Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CLIENT_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
    - master
    - prod

build_api:
  stage: build
  script:
    - docker build -t $API_IMAGE_NAME -f Dockerfile .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $API_IMAGE_NAME
  environment:
    name: $CI_COMMIT_REF_SLUG
  only:
    - master
    - prod

deploy_staging:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_STAGING_ENV --stack $RANCHER_STACK --service $RANCHER_ISARI_API_SERVICE --start-before-stopping
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_STAGING_ENV --stack $RANCHER_STACK --service $RANCHER_ISARI_CLIENT_SERVICE --start-before-stopping
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $STAGING_BASEURL
  only:
    - master

deploy_production:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_PRODUCTION_ENV --stack $RANCHER_STACK --service $RANCHER_ISARI_API_SERVICE --start-before-stopping
    - upgrade --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --rancher-url $RANCHER_URL --environment $RANCHER_PRODUCTION_ENV --stack $RANCHER_STACK --service $RANCHER_ISARI_CLIENT_SERVICE --start-before-stopping
  environment:
    name: $CI_COMMIT_REF_SLUG
    url: $PRODUCTION_BASEURL
  only:
    - prod