# Fake organization providing access to unfiltered data for central roles
[globalOrganization]
id = ''
name = 'Sciences Po'

# Match collection names to API endpoints and ES indices
[collections]
People = 'people'
Activity = 'activities'
Organization = 'organizations'

[specs]
validateOnStart = true

[http]
port = 8080
detailedErrors = false

[log]
format = 'combined'

[session]
secret = 'aizeoiniun'
ttl = 86400

[mongo]
url = 'mongodb://localhost/isari'

[elasticsearch]
# https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html
host = 'localhost:9200'
apiVersion = '2.3'
index = 'isari'
defaultSize = 10
maxSize = 5000

[ldap]
url = 'ldap://ldap-pprd.sciences-po.fr:389'
dn = 'DC=sciencespo,DC=fr'
bind_dn = 'cn=ACCOUNT, ou=ACCOUNT_TYPE, dc=sciencespo,dc=fr'
password = 'SECRET'
loginAtt = 'supannAliasLogin'
activeFlag = 'scpoAllActifSI'
# WARNING! USE WITH CAUTION!
# Set to true to fully disable LDAP, meaning login/password will be automatically accepted with no check
skip = false

[debug]
mongoose = true
