[http]
port = 8080
detailedErrors = true

[log]
format = 'dev'

[mongo]
url = 'mongodb://localhost/isaridev'

[elasticsearch]
index = 'isaridev'

[ldap]
url = 'ldap://ldapdevl.sciences-po.fr'
skip = true

[debug]
mongoose = true
